<a href="https://colab.research.google.com/github/Shahzodbey/real_projects/blob/main/ML_absenteeism.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Create Logistic Regression

## Import libraries

In [ ]:
import pandas as pd
import numpy as np

## Load the data

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/data science/notebooks/Absenteeism_preprocessed.csv')
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

## Create targets

In [ ]:
df['Absenteeism Time in Hours'].median()

3.0

In [ ]:
targets = np.where(df['Absenteeism Time in Hours'] > df['Absenteeism Time in Hours'].median(), 1, 0)

In [ ]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [ ]:
df['Excessive Absenteeism'] = targets

In [ ]:
df.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

### A comment on targets

In [ ]:
targets.sum() / targets.shape[0] # for logistic regression target's classes should be 50 to 50 or 60 to 40 proportion

0.45571428571428574

## Create Checkpoint

In [ ]:
data_with_targets = df.drop(['Absenteeism Time in Hours', 'Day of the week', 'Distance to Work', 'Daily Work Load Average'], axis=1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                     289   33               30          0         2     1   
1                     118   50               31          0         1     0   
2                     179   38               31          0         0     0   
3                     279   39               24          0         2     0   
4                     289   33               30          0         2     1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [ ]:
data_with_targets is df

False

## Select Inputs

In [ ]:
data_with_targets.shape

(700, 12)

In [ ]:
data_with_targets.iloc[:, :14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  \
0                       289   33               30          0         2     1   
1                       118   50               31          0         1     0   
2                       179   38               31          0         0     0   
3                       279   39               24          0         2     0   
4                       289   33               30          0         2     1   
..                      ...  ...              ...        ...       ...   ...   
695                     179   40               22          1         2     0   
696                     225   28               24          0         1     2   
697                     330   28               25          1         0     0   
698                     235   32               25          1         0     0   
699                     291   40               25          0         1     1   

     Excessive Absenteeism  
0                        1  
1                        0  
2                        0  
3                        1  
4                        0  
..                     ...  
695                      1  
696                      0  
697                      1  
698                      0  
699                      0  

[700 rows x 12 columns]

In [ ]:
data_with_targets.iloc[:, :-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pets  
0                       289   33               30          0         2     1  
1                       118   50               31          0         1     0  
2                       179   38               31          0         0     0  
3                       279   39               24          0         2     0  
4                       289   33               30          0         2     1  
..                      ...  ...              ...        ...       ...   ...  
695                     179   40               22          1         2     0  
696                     225   28               24          0         1     2  
697                     330   28               25          1         0     0  
698                     235   32               25          1         0     0  
699                     291   40               25          0         1     1  

[700 rows x 11 columns]

In [ ]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

## Standarize the inputs

In [ ]:
# from sklearn.preprocessing import StandardScaler

# absenteeism_scaler = StandardScaler()

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):

  def __init__(self,columns):
    self.scaler = StandardScaler()
    self.columns = columns
    self.mean = None
    self.var_ = None
  
  def fit(self, X, y=None):
    self.scaler.fit(X[self.columns], y)
    self.mean = np.mean(X[self.columns])
    self.var_ = np.var(X[self.columns])
    return self
  
  def transform(self, X, y=None,):
    init_col_orders = X.columns
    X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
    X_notscaled = X.loc[:, ~X.columns.isin(self.columns)]
    return pd.concat([X_notscaled, X_scaled], axis=1)[init_col_orders]

In [ ]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [ ]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

columns_toscale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [ ]:
absenteeism_scaler = CustomScaler(columns_toscale)

In [ ]:
absenteeism_scaler.fit(unscaled_inputs) # this calculate mean and std for each column

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pets'])

In [ ]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs) # this actually applys scaling

In [ ]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
..        ...       ...       ...       ...          ...   
695         1         0         0         0    -0.388293   
696         1         0         0         0    -0.388293   
697         1         0         0         0    -0.388293   
698         0         0         0         1    -0.388293   
699         0         0         0         1    -0.388293   

     Transportation Expense       Age  Body Mass Index  Education  Children  \
0                  1.005844 -0.536062         0.767431          0  0.880469   
1                 -1.574681  2.130803         1.002633          0 -0.019280   
2                 -0.654143  0.248310         1.002633          0 -0.919030   
3                  0.854936  0.405184        -0.643782          0  0.880469   
4                  1.005844 -0.536062         0.767431          0  0.880469   
..                      ...       ...              ...        ...       ...   
695               -0.654143  0.562059        -1.114186          1  0.880469   
696                0.040034 -1.320435        -0.643782          0 -0.019280   
697                1.624567 -1.320435        -0.408580          1 -0.919030   
698                0.190942 -0.692937        -0.408580          1 -0.919030   
699                1.036026  0.562059        -0.408580          0 -0.019280   

         Pets  
0    0.268487  
1   -0.589690  
2   -0.589690  
3   -0.589690  
4    0.268487  
..        ...  
695 -0.589690  
696  1.126663  
697 -0.589690  
698 -0.589690  
699  0.268487  

[700 rows x 11 columns]

## Train, Test split and shuffle

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_test_split(scaled_inputs, targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 139         1         0         0         0    -1.244823   
 126         0         0         0         1    -1.530333   
 352         1         0         0         0     1.610276   
 601         0         0         0         1    -1.244823   
 698         0         0         0         1    -0.388293   
 ..        ...       ...       ...       ...          ...   
 694         0         0         0         1    -0.388293   
 318         0         0         0         1     1.324766   
 539         0         0         0         1     1.324766   
 37          1         0         0         0     0.468236   
 652         0         0         1         0    -0.959313   
 
      Transportation Expense       Age  Body Mass Index  Education  Children  \
 139               -0.654143  0.248310         1.002633          0 -0.919030   
 126               -1.574681  0.091435         0.297027          0 -0.919030   
 352                0.1909

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=21, shuffle=True)

In [ ]:
print (x_train.shape, y_train.shape)

(560, 11) (560,)


In [ ]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [ ]:
reg = LogisticRegression()

reg.fit(x_train, y_train)

LogisticRegression()

In [ ]:
reg.score(x_test, y_test)

0.7857142857142857

## Check manually

In [ ]:
model_output = reg.predict(x_test)

In [ ]:
model_output == y_test

array([ True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True, False, False, False,  True, False, False,
        True,  True,  True, False, False,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,

In [ ]:
np.sum(model_output == y_test) / model_output.shape[0]

0.7857142857142857

## Intercept and Coefficient

In [ ]:
reg.intercept_

array([-1.61863017])

In [ ]:
reg.coef_

array([[ 2.70061717,  1.08541511,  2.97963734,  0.77840749,  0.0707637 ,
         0.54820084, -0.17520738,  0.31045391,  0.09455509,  0.44813489,
        -0.24171921]])

In [ ]:
feature_names = unscaled_inputs.columns.values

In [ ]:
summary_table = pd.DataFrame(columns=['Feature Name'], data=feature_names)

summary_table['Coefficients'] = np.transpose(reg.coef_)

In [ ]:
summary_table

Feature Name  Coefficients
0                 Reason_1      2.700617
1                 Reason_2      1.085415
2                 Reason_3      2.979637
3                 Reason_4      0.778407
4              Month Value      0.070764
5   Transportation Expense      0.548201
6                      Age     -0.175207
7          Body Mass Index      0.310454
8                Education      0.094555
9                 Children      0.448135
10                    Pets     -0.241719

In [ ]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature Name  Coefficients
0                Intercept     -1.618630
1                 Reason_1      2.700617
2                 Reason_2      1.085415
3                 Reason_3      2.979637
4                 Reason_4      0.778407
5              Month Value      0.070764
6   Transportation Expense      0.548201
7                      Age     -0.175207
8          Body Mass Index      0.310454
9                Education      0.094555
10                Children      0.448135
11                    Pets     -0.241719

## Testing the model

In [ ]:
reg.score(x_test, y_test)

0.7857142857142857

In [ ]:
predicted_proba = reg.predict_proba(x_test)

In [ ]:
predicted_proba

array([[0.80230962, 0.19769038],
       [0.21968795, 0.78031205],
       [0.76988145, 0.23011855],
       [0.88130779, 0.11869221],
       [0.62189313, 0.37810687],
       [0.87932456, 0.12067544],
       [0.78044357, 0.21955643],
       [0.36312538, 0.63687462],
       [0.54284026, 0.45715974],
       [0.35383319, 0.64616681],
       [0.69827947, 0.30172053],
       [0.22012886, 0.77987114],
       [0.34363777, 0.65636223],
       [0.77696202, 0.22303798],
       [0.86093045, 0.13906955],
       [0.7463853 , 0.2536147 ],
       [0.79908555, 0.20091445],
       [0.71324115, 0.28675885],
       [0.78388588, 0.21611412],
       [0.78388588, 0.21611412],
       [0.54284026, 0.45715974],
       [0.50551286, 0.49448714],
       [0.74770689, 0.25229311],
       [0.45106796, 0.54893204],
       [0.78388588, 0.21611412],
       [0.74770689, 0.25229311],
       [0.43192624, 0.56807376],
       [0.88130779, 0.11869221],
       [0.78728894, 0.21271106],
       [0.19711652, 0.80288348],
       [0.

## Save the model

In [ ]:
import pickle

In [ ]:
with open('model', 'wb') as file:
  pickle.dump(reg, file)

In [ ]:
with open('scaler', 'wb') as file:
  pickle.dump(absenteeism_scaler, file)